name: angular pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - src/**
      - .github/workflows/pipeline-angular.yml
      - 'nginx.conf'
      - 'Dockerfile'
      - 'package.json'
jobs:
  build-image:
    name: Build FE Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run:
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angular-ui:latest,${{ secrets.DOCKERHUB_USERNAME }}/angular-ui:${{ steps.extract_version.outputs.VERSION }}

